#**Data Structure Conversion**

In [ ]:
import numpy as np


### 1) List to array

In [ ]:
kaviya=["Chennai",21,9864457660]
type(kaviya)

list

In [ ]:
kaviya_arr=np.array(kaviya)
type(kaviya_arr)

numpy.ndarray

### 2) Tuple to array

In [ ]:
k=("Chennai",21,9864457660)
type(k)

tuple

In [ ]:
k_arr=np.array(k)

In [ ]:
type(k_arr)

numpy.ndarray

### 3) Dict to array

In [ ]:
dict={"a":"chennai","b":21}
type(dict)

dict

In [ ]:
dict_arr=np.array(dict)

In [ ]:
type(dict_arr)

numpy.ndarray

### 4) Set to array

In [ ]:
s={8,9,0,6,9,9}
type(s)


set

In [ ]:
s_arr=np.array(s)
type(s_arr)

numpy.ndarray

### **Using Numpy Function**

In [ ]:
a=np.array([5,6,7,8,9])
b=np.array([3,4,2,1,12])

In [ ]:

a+b

array([ 8, 10,  9,  9, 21])

In [ ]:
c=np.concatenate([a,b])
c

array([ 5,  6,  7,  8,  9,  3,  4,  2,  1, 12])

In [ ]:
cc=np.append(a,b)
cc

array([ 5,  6,  7,  8,  9,  3,  4,  2,  1, 12])

In [ ]:
d=np.vstack([a,b])
d

array([[ 5,  6,  7,  8,  9],
       [ 3,  4,  2,  1, 12]])

In [ ]:
e=np.hstack([a,b])
e

array([ 5,  6,  7,  8,  9,  3,  4,  2,  1, 12])

In [ ]:
t=np.transpose([a,b])
t

array([[ 5,  3],
       [ 6,  4],
       [ 7,  2],
       [ 8,  1],
       [ 9, 12]])

In [ ]:
s=np.array([[2,4,6],[3,5,8],[8,7,5]])
s

array([[2, 4, 6],
       [3, 5, 8],
       [8, 7, 5]])

In [ ]:
s.ndim

2

In [ ]:
s.shape

(3, 3)

In [ ]:
s.reshape(9,1)

array([[2],
       [4],
       [6],
       [3],
       [5],
       [8],
       [8],
       [7],
       [5]])

### Array Boardcasting  (arithmetic operation)

In [ ]:
s.sum()

48

In [ ]:
s.min()

2

In [ ]:
s.max()

8

In [ ]:
s.mean()         # In list mode and meadian function are not possible

5.333333333333333

In [ ]:
s.cumsum()       #cumlative frequency

array([ 2,  6, 12, 15, 20, 28, 36, 43, 48])

In [ ]:
arr_s=np.arange(1,100,2)
arr_s


array([ 1,  3,  5,  7,  9, 11, 13, 15, 17, 19, 21, 23, 25, 27, 29, 31, 33,
       35, 37, 39, 41, 43, 45, 47, 49, 51, 53, 55, 57, 59, 61, 63, 65, 67,
       69, 71, 73, 75, 77, 79, 81, 83, 85, 87, 89, 91, 93, 95, 97, 99])

###Dimensionality changes

In [ ]:
s

array([[2, 4, 6],
       [3, 5, 8],
       [8, 7, 5]])

In [ ]:
s.ndim

2

###Flatten()--- use to break the dimensionality eg: 2D-1D

In [ ]:
s_flat=s.flatten()
s_flat

array([2, 4, 6, 3, 5, 8, 8, 7, 5])

In [ ]:
s_flat.ndim

1

###Ravel()--- use to break highn dimensionality into single eg: 3D,4d..-1D

In [ ]:
s_ravel=s.ravel()
s_ravel

array([2, 4, 6, 3, 5, 8, 8, 7, 5])

In [ ]:
s_ravel.ndim

1

### Creating various kind of array

In [ ]:
emp_arr=np.empty((5,3))

In [ ]:
emp_arr

array([[5.05389801e-310, 0.00000000e+000, 0.00000000e+000],
       [0.00000000e+000, 9.48700996e+170, 1.16095484e-028],
       [1.10121846e-012, 1.69201561e+190, 7.57881487e-096],
       [6.03835792e+151, 1.46899930e+179, 9.08367237e+223],
       [1.16466228e-028, 9.90942922e+170, 6.32404027e-322]])

In [ ]:
a=[]
type(a)

list

In [ ]:
b=np.array(a)
b

array([], dtype=float64)

In [ ]:
g=np.empty(b)
g

array(4.68058668e-310)

In [ ]:
m=np.empty([])
m

array(4.68058668e-310)

In [ ]:
ls=np.linspace(1,2,23)
ls

array([1.        , 1.04545455, 1.09090909, 1.13636364, 1.18181818,
       1.22727273, 1.27272727, 1.31818182, 1.36363636, 1.40909091,
       1.45454545, 1.5       , 1.54545455, 1.59090909, 1.63636364,
       1.68181818, 1.72727273, 1.77272727, 1.81818182, 1.86363636,
       1.90909091, 1.95454545, 2.        ])

In [ ]:
lg=np.logspace(1,2,23)
lg

array([ 10.        ,  11.10336318,  12.32846739,  13.6887451 ,
        15.19911083,  16.87612476,  18.73817423,  20.80567538,
        23.101297  ,  25.65020906,  28.48035868,  31.6227766 ,
        35.11191734,  38.98603703,  43.28761281,  48.06380863,
        53.36699231,  59.25530976,  65.79332247,  73.05271543,
        81.11308308,  90.06280202, 100.        ])

In [ ]:
np.zeros((2,5,4))  # number of array, row, columns



array([[[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]],

       [[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]]])

In [ ]:
np.ones((6), dtype=int)

array([1, 1, 1, 1, 1, 1])

In [ ]:
np.ones((2,3,2))

array([[[1., 1.],
        [1., 1.],
        [1., 1.]],

       [[1., 1.],
        [1., 1.],
        [1., 1.]]])

In [ ]:
np.eye(3)   # Diagonal matrix

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

###Array in Indexing

In [ ]:
s

array([[2, 4, 6],
       [3, 5, 8],
       [8, 7, 5]])

In [ ]:
s[0:1]

array([[2, 4, 6]])

In [ ]:
s[1:3,2:4]

array([[8],
       [5]])

In [ ]:
s[0]

array([2, 4, 6])

In [ ]:
s[0:1,0:1]

array([[2]])

In [ ]:
s[1:1]

array([], shape=(0, 3), dtype=int64)

In [ ]:
s%2==0

array([[ True,  True,  True],
       [False, False,  True],
       [ True, False, False]])

In [ ]:
s[s%2==0]     # to show thw value if the conditions are true

array([2, 4, 6, 8, 8])